apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolerchart.fullname" . }}
  labels:
    {{- include "coolerchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "coolerchart.selectorLabels" . | nindent 4 }}
