apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myapp-source
  namespace: flux-system
spec:
  interval: 2m
  url: https://github.com/Nico0000000/Kubernetes-Spring
  ref:
    branch: main
